######################################################################
##
## Filename: tb_example_top.udo
## Created on: Tue Apr 08 05:43:14 PM PDT 2014
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
